name: lint

on: pull_request

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Set up Node 12.13.0
        uses: actions/setup-node@v1
        with:
            node-version: 12.13.0
      - name: Lint frontend code with ESLint
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          npm install
          npm run lint-frontend

  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Set up Node 12.13.0
        uses: actions/setup-node@v1
        with:
            node-version: 12.13.0
      - name: Lint backend code with Flake8
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          npm install
          npm run lint-backend
